### ISSUE TITLE
Description of CWL Airflow use case

### ISSUE THREAD

**Issue by tomLandry** [doutriaux1/wps_cwt#146]
Hello CWT! We have projects at OGC that calls for implementation of Workflows using CWL runners. We plan to use Toil, but I would like to know how you plan to use Airflow. Maybe there is a good opportunity for interoperability here.

Any sequence diagrams on this? Components diagrams?

**Comment by jasonb5** [comment]
Right now we're just investigating moving from Celery canvas to Airflow. The plan for the moment is to design an Airflow DAG that represents a single operation. This operation DAG will become a sub dag when a workflow is requested. This is just preliminary, so I don't have any diagrams put together yet. As for CWL, I found [cwl-airflow](https://github.com/Barski-lab/cwl-airflow), so there may be an opportunity there.

**Comment by tomLandry** [comment]
Well we're on a good page for CWL, and we can manage Celery too. Our CWL scripts wraps docker images (applications).
