### ISSUE TITLE
DescribeProcess on https://aims2.llnl.gov/wps

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#200]
Not sure where to post this issue, so I'm leaving it here...

When I do a describe process on aims2, I think there is an error in the returned schema.

Where we have:
ProcessDescription -> DataInputs -> Input -> ComplexOutput
I think we should have:
ProcessDescription -> DataInputs -> Input -> ComplexData

https://aims2.llnl.gov/wps/?request=DescribeProcess&service=WPS&identifier=CDAT.subset

**Comment by cehbrecht** [comment]
Example with ESGF API profile and using PyWPS:
https://bovec.dkrz.de/ows/proxy/pelican?Service=WPS&Request=DescribeProcess&Version=1.0.0&Identifier=pelican_subset

```
<Input minOccurs="0" maxOccurs="1">
                <ows:Identifier>variable</ows:Identifier>
                <ows:Title>variable</ows:Title>
                <ows:Abstract></ows:Abstract>
                <ComplexData maximumMegabytes="200">
                    <Default>
                        <Format>
                            <MimeType>application/json</MimeType>
                        </Format>
                    </Default>
                    <Supported>
                        <Format>
                            <MimeType>application/json</MimeType>
                        </Format>
                    </Supported>
                </ComplexData>
            </Input>
```
