### ISSUE TITLE
Single floating point results are stored as missing value.

### ISSUE THREAD

**Issue by doutriaux1** [doutriaux1/wps_cwt#209]
**Describe the bug**
It appears there is a bug when the operation returns a float, the resulting netcdf has only a missing value in it.

**To Reproduce**
take the "maximum" operator and ask for max over all dimensions (['lat', 'lon', 'time']) the resulting netcdf file as missing data as a result, even though averaging over 2 dims leads to an array with no missing values

**Expected behavior**
An array with only one valid value in it

**Additional context**
ran it from notebook maximum example.

**Comment by jasonb5** [comment]
~~This is still an issue.~~

This looks fixed now that we're using xarray, though opening the file using cdms2 it's unclear how to access the single value, XArray is fairly simple.

`xarray.open_dataset('...').pr.item()`

Replace `pr` with whatever the variable name is.
