### ISSUE TITLE
UI for dataset could be a bit clearer

### ISSUE THREAD

**Issue by doutriaux1** [doutriaux1/wps_cwt#210]
I type the opendap url for a file instead of . the dataset id, and i got no error but an empty list for variables. Probably we should raise an error and rename the pulldown from Dataset to Dataset ID

**Comment by nathanlcarlson** [comment]
+1 for Dataset -> Dataset ID

**Comment by jasonb5** [comment]
8cb50664c4ef6d8d7508eac0ce8381e77c8b5c59 fixes validating dataset id and displaying error if anything fails. The validation is just a simple regex for <Master ID>:<Data node>, so entering a URL no longer works.

**Comment by jasonb5** [comment]
We're retiring the webapp and will not fix.
