### ISSUE TITLE
CDAT.subset process output parameter is not a json

### ISSUE THREAD

**Issue by cehbrecht** [doutriaux1/wps_cwt#214]
**Describe the bug**
I have tried the `CDAT.subset` process of the "getting started" notebook. The wps output parameter returns a value like this (list of str):
```
['{"uri": "https://test.nc", "id": "tas|123"}']
```

... but it should be a json (no `''`):
```
[{"uri": "https://test.nc", "id": "tas|123"}]
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jasonb5** [comment]
I believe this has been fixed.
