### ISSUE TITLE
sync request does not wait until process has completed

### ISSUE THREAD

**Issue by cehbrecht** [doutriaux1/wps_cwt#215]
**Describe the bug**
When you send a *sync* WPS execute request the service returns a *ProcessAccepted* response. The service should wait with a response until the process has finished.

The current behavior of the service supports only *async* WPS execute requests.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jasonb5** [comment]
This is expected behavior, we've chosen to not support sync WPS execute requests. Rather we've built this behavior into the esgf-compute-api with the wait method of the Process class. 

If there's a use case for this behavior we can look into supporting it.
