### ISSUE TITLE
[Question] How to open new dataset?

### ISSUE THREAD

**Issue by lee1043** [doutriaux1/wps_cwt#216]
Hi, I was able to get my account on aims2 with valid token, and was able to reproduce a plot in the [example notebook](https://github.com/ESGF/esgf-compute-api/blob/master/examples/getting_started.ipynb). However, I couldn't figure out how to work with dataset from `esgf-node.llnl.gov` other than given example. 

I guess I am missing something, would you be available to help? Thank you in advance. 

### 1. Attempt with data's web address
I tried with the data with its address, `http://esgf.nccs.nasa.gov/thredds/fileServer/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r1i1p1f1/day/ua/gn/v20181015/ua_day_GISS-E2-1-G_historical_r1i1p1f1_gn_19500101-19591231.nc`, but was not successful.

```python
tas = cwt.Variable('http://esgf.nccs.nasa.gov/thredds/fileServer/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r1i1p1f1/day/ua/gn/v20181015/ua_day_GISS-E2-1-G_historical_r1i1p1f1_gn_19500101-19591231.nc', 'ua')
d0 = cwt.Domain(lat=(-90, 0), time=(0, 2000))
d0
```
> ```Domain(dimensions={'lat': Dimension(name='lat', start=-90, end=0, step=1, crs=CRS(name='values')), 'time': Dimension(name='time', start=0, end=2000, step=1, crs=CRS(name='values'))}, mask=None, name='e4f7d28e-8066-42f1-9b28-9802d16c2fef')```

```python
client.execute(proc, [tas], d0)
proc.wait()
```
> ```ProcessAccepted None```
> ```ProcessStarted Building 1 inputs 0```
> ```owslib.wps.WPSException : {'code': 'NoApplicableCode', 'locator': None, 'text': "Internal API call failed ErrorMessage(Error(title='500 Internal Server Error', content={'detail': 'Missing OAuth2 state, try authenticating with OAuth2 again'}))"}```
> ```ProcessFailed None```
> ```False```

### 2. Attempt with data's ID from the ESGF node
I tried with the ID of data given from the ESGF node, `hdl:21.14100/2903cb87-f9c6-4f6a-a259-47559f9b7f85`, but was not successful neither.

```python
tas =cwt.Variable('hdl:21.14100/2903cb87-f9c6-4f6a-a259-47559f9b7f85', 'ua')
client.execute(proc, [tas], d0)
proc.wait()
```
> ```ProcessAccepted None```
> ``` owslib.wps.WPSException : {'code': 'NoApplicableCode', 'locator': None, 'text': "No connection adapters were found for 'hdl:21.14100/2903cb87-f9c6-4f6a-a259-47559f9b7f85.dds'"}```
> ```ProcessFailed None```
> ```False```

**Comment by jasonb5** [comment]
@lee1043 For the first issue, the input must be accessible through OpenDAP. Swap "fileServer" for "dodsC" in the url and it will work. The error is very misleading and I'll fix that. 

As for the second issue the answer is the same as above, the file must be accessible through OpenDAP. This isn't very clear, it's only documented in the [FAQ](https://github.com/ESGF/esgf-compute-wps/blob/devel/FAQ.md#what-type-of-data-can-the-compute-service-consume) so I'll fix making the error message much clearer on what's happening.
