### ISSUE TITLE
Cross site request forgery (CSRF) protection is disabled 

### ISSUE THREAD

**Issue by Dhayalanb** [doutriaux1/wps_cwt#252]
**Describe the bug**
The CSRF middleware provided by django framework is disabled in the settings file
https://github.com/ESGF/esgf-compute-wps/blob/35b76eb3deb422fe2c94c8b9b5b0725a6c89c231/compute/compute_wps/settings.py : 217

The code that adds CSRF middleware is also commented out:
```
# if not DEBUG:
#     MIDDLEWARE.insert(4, 'django.middleware.csrf.CsrfViewMiddleware')
```

**Fix**:
 Add django.middleware.csrf.CsrfViewMiddleware to the MIDDLEWARE global variable.

**Comment by jasonb5** [comment]
Thanks for reporting this, we've reenabled the middleware.
