### ISSUE TITLE
EDAS error opening cdat output

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#66]
&lt;![CDATA[ NetCDF: Bad chunk sizes. nc_def_var_chunking on variable time: nasa.nccs.esgf.process.DataContainer$.factory(Task.scala:957) nasa.nccs.esgf.process.TaskRequest$$anonfun$6.apply(Task.scala:209) nasa.nccs.esgf.process.TaskRequest$$anonfun$6.apply(Task.scala:209) scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251) scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251) scala.collection.immutable.List.foreach(List.scala:318) scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251) scala.collection.AbstractTraversable.flatMap(Traversable.scala:105) nasa.nccs.esgf.process.TaskRequest$.apply(Task.scala:209) nasa.nccs.esgf.wps.ProcessManager.executeProcess(process.scala:65) nasa.nccs.edas.portal.EDASapp.execute(application.scala:98) nasa.nccs.edas.portal.EDASPortal.run(EDASPortal.java:296) nasa.nccs.edas.portal.EDASApplication$.main(application.scala:198) nasa.nccs.edas.portal.EDASApplication.main(application.scala) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:606) org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731) org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181) org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206) org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121) org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) ]]&gt;

netcdf dbcdd48f-0d55-4f92-a5bd-11ad9f68c283 {
dimensions:
        time = UNLIMITED ; // (11 currently)
        bound = 2 ;
        plev = 17 ;
        lat = 96 ;
        lon = 145 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:realtopology = "linear" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
                time:units = "days since 1850-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:axis = "T" ;
        double time_bnds(time, bound) ;
        double plev(plev) ;
                plev:realtopology = "linear" ;
                plev:positive = "down" ;
                plev:long_name = "pressure" ;
                plev:standard_name = "air_pressure" ;
                plev:units = "Pa" ;
                plev:axis = "Z" ;
        double lat(lat) ;
                lat:bounds = "lat_bnds" ;
                lat:realtopology = "linear" ;
                lat:long_name = "latitude" ;
                lat:standard_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
        double lat_bnds(lat, bound) ;
        double lon(lon) ;
                lon:bounds = "lon_bnds" ;
                lon:modulo = 360. ;
                lon:realtopology = "circular" ;
                lon:long_name = "longitude" ;
                lon:standard_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:topology = "circular" ;
        double lon_bnds(lon, bound) ;
        float wap(time, plev, lat, lon) ;
                wap:comment = "commonly referred to as \"\"omega\"\", this represents the vertical component of velocity in pressure coordinates (positive down)" ;
                wap:_FillValue = 1.e+20f ;
                wap:missing_value = 1.00000002004088e+20 ;
                wap:original_name = "OMEGA" ;
                wap:associated_files = "baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: gridspec_atmos_fx_NorESM1-ME_historical_r0i0p0.nc areacella: areacella_fx_NorESM1-ME_historical_r0i0p0.nc" ;
                wap:long_name = "omega (=dp/dt)" ;
                wap:standard_name = "lagrangian_tendency_of_air_pressure" ;
                wap:cell_methods = "time: mean" ;
                wap:cell_measures = "area: areacella" ;
                wap:units = "Pa s-1" ;
                wap:original_units = "Pa/s" ;
                wap:history = "2014-03-19T16:29:31Z altered by CMOR: Converted units from \'Pa/s\' to \'Pa s-1\'. 2014-03-19T16:29:31Z altered by CMOR: replaced missing value flag (1e+20) with standard missing value (1e+20). 2014-03-19T16:29:31Z altered by CMOR: Converted type from \'d\' to \'f\'." ;

// global attributes:
                :Conventions = "CF-1.0" ;
}

**Comment by jasonb5** [comment]
Looks like this was a size issue.

**Comment by jasonb5** [comment]
New issue https://gist.github.com/f5f1d0fc06b5bbd6ce68e01981d89cf3

**Comment by ThomasMaxwell** [comment]
Jason,
   I’ve implemented a different format for specifying axes- using the chars x,y,z,t.   They can be either concatenated, i.e. “xzt”, or comma-separated, i.e. “x,y,z”.   Is your format “longitude|latitude|plev” specified in the esgf or wps spec?

— Tom

**Comment by jasonb5** [comment]
Yea we've been using | to separate multiple values. As for the names we
left it open, as long as we can find the name in the netcdf file then its
valid. CDMS2 will accept longitude, lon, l or x as the axis id.

Here's a link
https://esgf-compute-api.readthedocs.io/en/latest/cwt.compat.html#id5, the
original document didn't really define how extra parameters were to be
passed since the operations definition was incomplete.

I can just map everything to "x, y, z, t" and then change the separator
when sending to EDAS for the time.

At the F2F I think we might need to revisit this CWT spec.

**Comment by jasonb5** [comment]
Figured out why I wasn't getting messages back from EDAS. 

I had to use:
``` python
socket.setsockopt(zmq.SUBSCRIBE, '{}'.format(job_id))
```
rather than
``` python
socket.subscribe('{}'.format(job_id))
```

I also switch from socket.poll to Poller class.
