### ISSUE TITLE
Discuss how we should handle datasets that are not hosted with OpenDAP.

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#81]

**Comment by doutriaux1** [comment]
let's bring that up at next telco and definitely at F2F

**Comment by jasonb5** [comment]
For the 2.0.0 version only DAP or local files will be supported.

**Comment by jasonb5** [comment]
Moving this to the 3.0.0 milestone for discussion.

**Comment by jasonb5** [comment]
We're leaving this at support for local netcdf files and opendap urls. We're looking into supporting Visus as an input format.
